name:                sqlparsing
version:             0.1.0.0
github:              "autcrock/sqlparsing"
license:             BSD3
author:              "Mike Thomas"
maintainer:          "mjt464@gmail.com"
copyright:           "All rights reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/autcrock/sqlparsing#readme>

dependencies:
- base >= 4.7 && < 5
- simple-sql-parser >= 0.6.0
- pretty-show
- strict

library:
  source-dirs: src

executables:
  sqlparsing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sqlparsing

tests:
  sqlparsing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sqlparsing
